spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    #**************druid 配置****************
    druid:
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall #log4j
      #最大活跃数
      max-active: 20
      #初始化数量
      initial-size: 1
      #最大连接等待超时时间
      max-wait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      min-idle: 1
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    #**************druid 配置****************


  jpa:
    database: mysql
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
